name: publish python package to PyPI

on:  # 这里我设置了两个事件，一般的push tag以v开头，用来测试发布，而release用来正式发布
  release:
    types: [published]
  push:
    # Alternative: only build for tags.
    tags:
      - 'v*'
jobs:
  build:  # 简化为单一构建任务
    name: Build distribution packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: python -m build
      
    - name: Check package
      run: |
        python -m twine check dist/*
        
    - uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  upload:  # 上传到PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # 这里很重要，因为启用了PyPI白名单，需要将临时生成的token写到任务程序里
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/

    - name: publish to PYPI
      if: github.event_name == 'release' && github.event.action == 'published'  # 有了这句话才能只在发布的时候执行
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        packages-dir: dist/